chore(ios15): adding ios 15 ui nightly tests

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -15,6 +15,15 @@ pipelines:
       # Run multiple tests on simulators in parallel
       - run-test-groups: {}
       - deploy-test-results: {}
+
+  qa-build-test-nightly-pipeline:
+    stages:
+      # Build a qa build, and build a test build in parallel
+      - build-and-test: {}
+      # Run multiple tests on simulators in parallel
+      - run-test-groups-nightly: {}
+      - deploy-test-results-nightly: {}
+  
   # Will create an app store capabale build, but release it to Internal Testing users in Testflight.
   # Intended to run nightly.
   nightly-internal-pipeline:
@@ -40,9 +49,23 @@ stages:
       - run-tests-ui-2: {}
       - run-tests-ui-3: {}
 
+  run-test-groups-nightly:
+    workflows:
+      - run-tests-unit: {}
+      - run-tests-ui-1: {}
+      - run-tests-ui-2: {}
+      - run-tests-ui-3: {}
+      - run-tests-ui-1-legacy: {}
+      - run-tests-ui-2-legacy: {}
+      - run-tests-ui-3-legacy: {}
+
   deploy-test-results:
     workflows:
       - deploy-test-results: {}
+
+  deploy-test-results-nightly:
+    workflows:
+      - deploy-test-results-nightly: {}
 
   release-build:
     workflows:
@@ -127,6 +150,24 @@ workflows:
       - pull-intermediate-files@1:
           inputs:
             - artifact_sources: build-and-test.test-build
+
+  # Helper step to install the last simulator version
+  _install_past_ios:
+    steps:
+      - script@1:
+          inputs:
+            - content: |
+                #!/usr/bin/env bash
+
+                # fail if any commands fails
+                set -e
+                
+                brew tap robotsandpencils/made
+                brew install robotsandpencils/made/xcodes
+                
+                echo "Install iOS 15 sim"
+                sudo xcodes runtimes install "iOS 15.5"
+
 
   # Helper step to start snowplow
   _start_snowplow:
@@ -350,6 +391,64 @@ workflows:
           inputs:
             - pipeline_intermediate_files: '$BITRISE_XCRESULT_PATH:BITRISE_UITESTS_3_XCRESULT_PATH'
 
+
+  run-tests-ui-1-legacy:
+    meta:
+      bitrise.io:
+        machine_type_id: g2-m1-max.5core
+    before_run:
+      - _install_past_ios
+      - _pull_test_bundle
+      - _start_snowplow
+    steps:
+      - xcode-test-without-building:
+          timeout: 1200 #20 minutes
+          title: UI Test Suite 1 Legacy
+          inputs:
+            - xctestrun: '${BITRISE_TEST_BUNDLE_PATH}/Pocket (iOS)_UITests_iphonesimulator16.2-arm64-x86_64.xctestrun'
+            - destination: platform=iOS Simulator,name=iPhone 13,OS=15.5
+      - deploy-to-bitrise-io@2.1.1:
+          inputs:
+            - pipeline_intermediate_files: '$BITRISE_XCRESULT_PATH:BITRISE_UITESTS_1_LEGACY_XCRESULT_PATH'
+
+  run-tests-ui-2-legacy:
+    meta:
+      bitrise.io:
+        machine_type_id: g2-m1-max.5core
+    before_run:
+      - _install_past_ios
+      - _pull_test_bundle
+      - _start_snowplow
+    steps:
+      - xcode-test-without-building:
+          timeout: 1200 #20 minutes
+          title: UI Test Suite 2 Legacy
+          inputs:
+            - xctestrun: '${BITRISE_TEST_BUNDLE_PATH}/Pocket (iOS)_UITests-2_iphonesimulator16.2-arm64-x86_64.xctestrun'
+            - destination: platform=iOS Simulator,name=iPhone 13,OS=15.5
+      - deploy-to-bitrise-io@2.1.1:
+          inputs:
+            - pipeline_intermediate_files: '$BITRISE_XCRESULT_PATH:BITRISE_UITESTS_2_LEGACY_XCRESULT_PATH'
+
+  run-tests-ui-3-legacy:
+    meta:
+      bitrise.io:
+        machine_type_id: g2-m1-max.5core
+    before_run:
+      - _install_past_ios
+      - _pull_test_bundle
+      - _start_snowplow
+    steps:
+      - xcode-test-without-building:
+          timeout: 1200 #20 minutes
+          title: UI Test Suite 3 Legacy
+          inputs:
+            - xctestrun: '${BITRISE_TEST_BUNDLE_PATH}/Pocket (iOS)_UITests-3_iphonesimulator16.2-arm64-x86_64.xctestrun'
+            - destination: platform=iOS Simulator,name=iPhone 13,OS=15.5
+      - deploy-to-bitrise-io@2.1.1:
+          inputs:
+            - pipeline_intermediate_files: '$BITRISE_XCRESULT_PATH:BITRISE_UITESTS_3_LEGACY_XCRESULT_PATH'
+
   deploy-test-results:
     steps:
       - pull-intermediate-files@1:
@@ -362,6 +461,29 @@ workflows:
                 set -eo pipefail
 
                 xcrun xcresulttool merge "${BITRISE_UITESTS_1_XCRESULT_PATH}" "${BITRISE_UITESTS_2_XCRESULT_PATH}" "${BITRISE_UITESTS_3_XCRESULT_PATH}" "${BITRISE_UNIT_XCRESULT_PATH}"  --output-path "merged.xcresult"
+
+                envman add --key BITRISE_XCRESULT_PATH --value "$(pwd)/merged.xcresult"
+      - custom-test-results-export@0:
+          inputs:
+            - search_pattern: '*'
+            - base_path: $BITRISE_XCRESULT_PATH
+            - test_name: Pocket Tests
+      - deploy-to-bitrise-io@2.1.1:
+          inputs:
+            - pipeline_intermediate_files: '$BITRISE_XCRESULT_PATH:BITRISE_XCRESULT_PATH'
+
+  deploy-test-results-nightly:
+    steps:
+      - pull-intermediate-files@1:
+          inputs:
+            - artifact_sources: run-test-groups-nightly\..*
+      - script@1:
+          inputs:
+            - content: |
+                #!/usr/bin/env bash
+                set -eo pipefail
+
+                xcrun xcresulttool merge "${BITRISE_UITESTS_1_XCRESULT_PATH}" "${BITRISE_UITESTS_2_XCRESULT_PATH}" "${BITRISE_UITESTS_3_XCRESULT_PATH}" "${BITRISE_UITESTS_1_LEGACY_XCRESULT_PATH}" "${BITRISE_UITESTS_2_LEGACY_XCRESULT_PATH}" "${BITRISE_UITESTS_3_LEGACY_XCRESULT_PATH}" "${BITRISE_UNIT_XCRESULT_PATH}"  --output-path "merged.xcresult"
 
                 envman add --key BITRISE_XCRESULT_PATH --value "$(pwd)/merged.xcresult"
       - custom-test-results-export@0:
