update birtise.yml

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -146,15 +146,16 @@ workflows:
     steps:
         - script@1:
             inputs:
-                - content: |
-                    #!/usr/bin/env bash
-                    # fail if any commands fails
-                    set -e
-                    # testing coverage
-                    xcrun xcresulttool version
-                    xcrun xcresulttool metadata get --path merged.xcresult
-                    xcrun xcresulttool graph --path merged.xcresult
-                    xcrun xccov view --report --json /Users/vagrant/git/merged.xcresult > afile
+            - content: |
+                #!/usr/bin/env bash
+                # fail if any commands fails
+                set -e
+                # testing coverage
+                xcrun xcresulttool version
+                xcrun xcresulttool metadata get --path merged.xcresult
+                xcrun xcresulttool graph --path merged.xcresult
+                xcrun xccov view --report --json /Users/vagrant/git/merged.xcresult > afile
+
       - activate-ssh-key@4: {}
       - git-clone@8: {}
       - script@1:
